
# @Author aryakd
# To validate docker compose file : docker-compose -f docker-compose.yml config
# To start : docker compose up -d activemq
# To stop : docker compose stop
# Note : ports must not have spaces on either sides of ":"

services:
  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      - 61616:61616
      - 8161:8161

  rabbit:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
